apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-frontend-ingress
  namespace: local-ai
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - admin.ai.kinvee.in
      secretName: admin-frontend-tls
  rules:
    - host: admin.ai.kinvee.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-frontend
                port:
                  number: 80
